# Default values for generic values.yaml
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: meep-demo2-svc-zoneX-edgeX-svc

deployment:
  name: zoneX-edgeX-svc
 
service:
  name: zoneX-edgeX-svc
