{{- if .Values.service.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}}
  namespace: {{.Values.service.namespace}}
  labels:
    {{- range $key, $value := .Values.service.labels}}
    {{$key}}: {{$value | quote}}
    {{- end}}
spec:
  type: {{ .Values.service.type }}
  selector:
  {{- range $key, $value := .Values.service.selector}}
    {{$key}}: {{$value}}
  {{- end}}
  ports:
  {{- range .Values.service.ports}}
  - name: {{.name}}
    port: {{.port}}
    targetPort: {{.targetPort}}
    protocol: {{.protocol}}
  {{- if eq $.Values.service.type "NodePort"}}
    nodePort: {{.nodePort}}
  {{- end}}
  {{- end}}
{{- end}}

{{if .Values.service.meservice.enabled}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.meservice.name}}
  namespace: {{.Values.service.namespace}}
  labels:
    {{- range $key, $value := .Values.service.labels}}
    {{$key}}: {{$value | quote}}
    {{- end}}
spec:
  type: {{.Values.service.meservice.type}}
  selector:
  {{- range $key, $value := .Values.service.meservice.selector}}
    {{$key}}: {{$value}}
  {{- end}}
  ports:
  {{- range .Values.service.ports}}
  - name: {{.name}}
    port: {{.port}}
    targetPort: {{.targetPort}}
    protocol: {{.protocol}}
  {{- if eq $.Values.service.meservice.type "NodePort"}}
    nodePort: {{.nodePort}}
  {{- end}}
  {{- end}}
{{end}}

{{if .Values.external.enabled}}
{{- range .Values.external.ingressservicemap}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{.name}}
  namespace: default
spec:
  type: NodePort
  selector:
    {{- range $key, $value := $.Values.external.selector}}
    {{$key}}: {{$value}}
    {{- end}}
  ports:
  - port: {{.port}}
    targetPort: {{.targetPort}}
    protocol: {{.protocol}}
    nodePort: {{.nodePort}}
{{- end}}
{{- range .Values.external.egressservicemap}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{.name}}
  namespace: default
spec:
  type: ClusterIP
  selector:
    {{- range $key, $value := $.Values.external.selector}}
    {{$key}}: {{$value}}
    {{- end}}
  ports:
  - port: {{.port}}
    targetPort: {{.targetPort}}
    protocol: {{.protocol}}
{{- end}}
{{- end}}



