/*
 * Copyright (c) 2022  The AdvantEDGE Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * MEC Demo 3 API
 * Demo 3 is an edge application that can be used with AdvantEDGE or ETSI MEC Sandbox to demonstrate MEC011 and MEC021 usage
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MecDemo3Api);
  }
}(this, function(expect, MecDemo3Api) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ApplicationInstance', function() {
      beforeEach(function() {
        instance = new MecDemo3Api.ApplicationInstance();
      });

      it('should create an instance of ApplicationInstance', function() {
        // TODO: update the code to test ApplicationInstance
        expect(instance).to.be.a(MecDemo3Api.ApplicationInstance);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property config (base name: "config")', function() {
        // TODO: update the code to test the property config
        expect(instance).to.have.property('config');
        // expect(instance.config).to.be(expectedValueLiteral);
      });

      it('should have the property ip (base name: "ip")', function() {
        // TODO: update the code to test the property ip
        expect(instance).to.have.property('ip');
        // expect(instance.ip).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property mecReady (base name: "mecReady")', function() {
        // TODO: update the code to test the property mecReady
        expect(instance).to.have.property('mecReady');
        // expect(instance.mecReady).to.be(expectedValueLiteral);
      });

      it('should have the property mecTerminated (base name: "mecTerminated")', function() {
        // TODO: update the code to test the property mecTerminated
        expect(instance).to.have.property('mecTerminated');
        // expect(instance.mecTerminated).to.be(expectedValueLiteral);
      });

      it('should have the property amsResource (base name: "amsResource")', function() {
        // TODO: update the code to test the property amsResource
        expect(instance).to.have.property('amsResource');
        // expect(instance.amsResource).to.be(expectedValueLiteral);
      });

      it('should have the property subscriptions (base name: "subscriptions")', function() {
        // TODO: update the code to test the property subscriptions
        expect(instance).to.have.property('subscriptions');
        // expect(instance.subscriptions).to.be(expectedValueLiteral);
      });

      it('should have the property offeredService (base name: "offeredService")', function() {
        // TODO: update the code to test the property offeredService
        expect(instance).to.have.property('offeredService');
        // expect(instance.offeredService).to.be(expectedValueLiteral);
      });

      it('should have the property discoveredServices (base name: "discoveredServices")', function() {
        // TODO: update the code to test the property discoveredServices
        expect(instance).to.have.property('discoveredServices');
        // expect(instance.discoveredServices).to.be(expectedValueLiteral);
      });

    });
  });

}));
