# Copyright (c) 2019
# InterDigital Communications, Inc.
# All rights reserved.
#
# The information provided herein is the proprietary and confidential
# information of InterDigital Communications, Inc.

FROM debian:9.6-slim
ADD meep-webhook /meep-webhook
ENTRYPOINT /meep-webhook
