/*
 * Copyright (c) 2020  InterDigital Communications, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the \"License\");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an \"AS IS\" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * MEC Application Support API
 *
 * The ETSI MEC ISG MEC011 MEC Application Support API described using OpenAPI
 *
 * API version: 2.1.1
 * Contact: cti_support@etsi.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// This type represents the destination interface. If the action is FORWARD_DECAPSULATED, FORWARD_ENCAPSULATED or PASSTHROUGH one value shall be provided. If the action is DUPLICATE_DECAPSULATED or DUPLICATE_ENCAPSULATED, two values shall be provided. If the action is DROP, no value shall be provided.
type DestinationInterface struct {
	// Type of the interface
	InterfaceType string      `json:"interfaceType"`
	TunnelInfo    *TunnelInfo `json:"tunnelInfo,omitempty"`
	// Source address identifies the MAC address of the interface
	SrcMacAddress string `json:"srcMacAddress,omitempty"`
	// Destination address identifies the MAC address of the interface
	DstMacAddress string `json:"dstMacAddress,omitempty"`
	// IP address of the remote destination
	DstIpAddress string `json:"dstIpAddress,omitempty"`
}
