/*
 * MEEP Controller REST API
 *
 * MEEP Controller REST API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

import (
	"net/http"
)

func GetMeepSettings(w http.ResponseWriter, r *http.Request) {
	ceGetMeepSettings(w, r)
}

func SetMeepSettings(w http.ResponseWriter, r *http.Request) {
	ceSetMeepSettings(w, r)
}
