/*
 * Copyright (c) 2019  InterDigital Communications, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the \"License\");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an \"AS IS\" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * AdvantEDGE Metrics Service REST API
 *
 * Metrics Service provides metrics about the active scenario <p>**Micro-service**<br>[meep-metrics-engine](https://github.com/InterDigitalInc/AdvantEDGE/tree/master/go-apps/meep-metrics-engine) <p>**Type & Usage**<br>Platform Service used by control/monitoring software and possibly by edge applications that require metrics <p>**Details**<br>API details available at _your-AdvantEDGE-ip-address:30000/api_ <p>**Default Port**<br>`30005`
 *
 * API version: 1.0.0
 * Contact: AdvantEDGE@InterDigital.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

type LogResponseData struct {

	// Number of packets received since last log event
	Rx int32 `json:"rx,omitempty"`

	// Number of bytes received since last log event
	RxBytes int32 `json:"rxBytes,omitempty"`

	// Throughput measured between 2 pods in Mbits/seconds
	Throughput float32 `json:"throughput,omitempty"`

	// Number of packets loss between2 pods as a percentage
	PacketLoss string `json:"packet-loss,omitempty"`

	// Latency measured betwen 2 pods in ms
	Latency int32 `json:"latency,omitempty"`

	// New poa affected by a mobility event
	NewPoa string `json:"newPoa,omitempty"`

	// Old poa affected by a mobility event
	OldPoa string `json:"oldPoa,omitempty"`
}
