appVersion: 2.1.1
description: A database featuring seamless multi-master sync, that scales from big
  data to mobile, with an intuitive HTTP/JSON API and designed for reliability.
home: https://couchdb.apache.org/
icon: http://couchdb.apache.org/CouchDB-visual-identity/logo/CouchDB-couch-symbol.svg
maintainers:
- email: kocolosk@apache.org
  name: kocolosk
name: couchdb
sources:
- https://github.com/apache/couchdb
- https://github.com/kocolosk/couchdb-statefulset-assembler
version: 0.1.6
