apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      dummy: "dummy"
  template:
    metadata:
      namespace: default
      labels:
        dummy: "dummy"

    spec:
      serviceAccountName: meep-user
      containers:
        - name: {{ .Values.deployment.name }}
          image: gophernet/iperf-server
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - -c
            - export; iperf -s -p $IPERF_SERVICE_PORT;
