kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  namespace: default
  labels:
    dummy: "dummy"
spec:
  type: ClusterIP
  selector:
    dummy: "dummy"
  ports:
  - name: port-80
    port: 80
    targetPort: 80
    protocol: UDP

