# Copyright (c) 2019
# InterDigital Communications, Inc.
# All rights reserved.
#
# The information provided herein is the proprietary and confidential
# information of InterDigital Communications, Inc.

FROM debian
COPY ./meep-virt-engine /meep-virt-engine
ENTRYPOINT /meep-virt-engine
