/*
 * ETSI GS MEC 012 - Radio Network Information API
 *
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * API version: 2.1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

type CellChangeNotification struct {
	// 0 to N identifiers to associate the event for a specific UE or flow.
	AssociateId []AssociateId `json:"associateId,omitempty"`
	// Indicate the status of the UE handover procedure. Values are defined as following: <p>1 = IN_PREPARATION. <p>2 = IN_EXECUTION. <p>3 = COMPLETED. <p>4 = REJECTED. <p>5 = CANCELLED.
	HoStatus int32 `json:"hoStatus"`
	// Shall be set to \"CellChangeNotification\".
	NotificationType string `json:"notificationType"`

	SrcEcgi *Ecgi `json:"srcEcgi"`

	TempUeId *CellChangeNotificationTempUeId `json:"tempUeId,omitempty"`

	TimeStamp *TimeStamp `json:"timeStamp,omitempty"`
	// E-UTRAN Cell Global Identifier of the target cell. NOTE: Cardinality N is valid only in case of statuses IN_PREPARATION, REJECTED and CANCELLED.
	TrgEcgi []Ecgi `json:"trgEcgi"`
}
