/*
 * ETSI GS MEC 012 - Radio Network Information API
 *
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * API version: 2.1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

type Plmn struct {
	// The Mobile Country Code part of PLMN Identity as defined in ETSI TS 136 413 [i.3].
	Mcc string `json:"mcc"`
	// The Mobile Network Code part of PLMN Identity as defined in ETSI TS 136 413 [i.3].
	Mnc string `json:"mnc"`
}
