/*
 * ETSI GS MEC 012 - Radio Network Information API
 *
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * API version: 2.1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

// S1 bearer information on eNB side as defined below.
type S1BearerInfoEnbInfo struct {
	// eNB transport layer address of this S1 bearer.
	IpAddress string `json:"ipAddress"`
	// eNB GTP-U TEID of this S1 bearer.
	TunnelId string `json:"tunnelId"`
}
