/*
 * MEEP Demo App API
 *
 * This is the MEEP Demo App API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

// Unique Identifier for a notification subscription.  Created by the MEC Location Service and used to reference an individual subscription
type SubscriptionId struct {
}
