{
 "title": "Custom AdvantEDGE Dashboard v5",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "Scenario", "query": "influxdb" },
   {
    "name": "src",
    "label": "Source Node",
    "query": "show tag values from network with key = \"src\""
   },
   {
    "name": "dest",
    "label": "Destination node",
    "query": "show tag values from network with key = \"dest\""
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput & Latency",
   "type": "graph",
   "description": "Shows latency & Throughput between UE1 & Fog1",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"lat\") FROM \"network\" WHERE (\"src\" =~ /^$src$/ AND \"dest\" =~ /^$dest$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    },
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "tput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput (Mbps)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "tput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT type,event from events WHERE $timeFilter ORDER BY time ASC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}