{
 "title": "Network Metrics Aggregation",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "database", "query": "show databases" },
   {
    "name": "src",
    "query": "show tag values on $database from network with key = \"src\""
   }
  ]
 },
 "panels": [
  {
   "title": "Inter-process Latency Aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Latencies",
   "type": "graph",
   "description": "Shows latency & Throughput between source & destination applications",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "alias": "[[tag_dest]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$scenario$/",
     "query": "SELECT lat FROM $database.autogen.network WHERE (\"src\" =~ /^$src$/) AND $timeFilter GROUP BY dest",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Inter-process Throughput Aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Up-Link",
   "type": "graph",
   "description": "Shows Up-Link Throughput from selected source",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "alias": "[[tag_dest]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT ul FROM $database.autogen.network WHERE (\"src\" =~ /^$src$/) AND $timeFilter GROUP BY dest",
     "select": [
      [
       { "params": [ "ul" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Down-Link",
   "type": "graph",
   "description": "Shows Down-Link Throughput to selected source",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "alias": "[[tag_dest]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT dl FROM $database.autogen.network WHERE (\"src\" =~ /^$src$/) AND $timeFilter GROUP BY dest",
     "select": [
      [
       { "params": [ "dl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Events",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "measurement": "events",
     "query": "SELECT type,description FROM $database.autogen.events WHERE $timeFilter ORDER BY time desc LIMIT 100",
     "select": [
      [
       { "params": [ "event" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}