{
 "title": "Platform (AdvantEDGE)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(metrics_http_request_duration_count, svc) "
   }
  ]
 },
 "panels": [
  { "title": "Sandbox Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sandbox Creation Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT createtime FROM global_sandbox_metrics.autogen.sbox WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Sandbox Creation Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mon_engine_sbox_create_duration_sum[$__range])) / sum(increase(mon_engine_sbox_create_duration_count[$__range]))"
    }
   ]
  },
  {
   "title": "Sandbox Creation Time Distribution (seconds)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(mon_engine_sbox_create_duration_bucket[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Platform API Requests & Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  { "title": "Requests", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 9 } },
  { "title": "Notifications", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 9 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(metrics_http_request_duration_count{svc=~\"$service\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Request Response Codes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(metrics_http_request_duration_count{svc=~\"$service\",status=~\"2.*\"}[$__range])) or vector(0)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(metrics_http_request_duration_count{svc=~\"$service\",status=~\"3.*\"}[$__range])) or vector(0)",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(metrics_http_request_duration_count{svc=~\"$service\",status=~\"4.*\"}[$__range])) or vector(0)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(metrics_http_request_duration_count{svc=~\"$service\",status=~\"5.*\"}[$__range])) or vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Total Notifications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(metrics_http_notification_duration_count{svc=~\"$service\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Notification Response Codes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(metrics_http_notification_duration_count{svc=~\"$service\",status=~\"2.*\"}[$__range])) or vector(0)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(metrics_http_notification_duration_count{svc=~\"$service\",status=~\"3.*\"}[$__range])) or vector(0)",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(metrics_http_notification_duration_count{svc=~\"$service\",status=~\"4.*\"}[$__range])) or vector(0)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(metrics_http_notification_duration_count{svc=~\"$service\",status=~\"5.*\"}[$__range])) or vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Top 10 Requests",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by (svc,path,method) (increase(metrics_http_request_duration_count{svc=~\"$service\"}[$__range]))))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Top 10 Notifications",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by (svc,notif) (increase(metrics_http_notification_duration_count{svc=~\"$service\"}[$__range]))))",
     "legendFormat": "{{svc}} | {{notif}}"
    }
   ]
  },
  {
   "title": "Request Duration Distribution (ms)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(metrics_http_request_duration_bucket{svc=~\"$service\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Notification Processing Time Distribution (ms)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(metrics_http_notification_duration_bucket{svc=~\"$service\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Top 10 Highest Average Request Processing Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(rate(metrics_http_request_duration_sum{svc=~\"$service\"}[$__range]) / rate(metrics_http_request_duration_count{svc!=\"Auth Service\"}[$__range])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Highest Average Notification Processing Times",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(avg by (svc,notif) (rate(metrics_http_notification_duration_sum{svc=~\"$service\"}[$__range]) / rate(metrics_http_notification_duration_count{svc=~\"$service\"}[$__range]))))",
     "legendFormat": "{{svc}} | {{notif}}"
    }
   ]
  }
 ]
}