{
 "title": "Players-Metrics-1-nofps",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "database", "query": "show databases" },
   {
    "name": "src1",
    "query": "show tag values on $database from network with key = \"src\""
   },
   {
    "name": "src2",
    "query": "show tag values on $database from network with key = \"src\""
   },
   {
    "name": "dest1",
    "query": "show tag values on $database from network with key = \"dest\""
   },
   {
    "name": "dest2",
    "query": "show tag values on $database from network with key = \"dest\""
   }
  ]
 },
 "panels": [
  { "title": "Player 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"lat\" FROM $database.autogen.network WHERE (\"src\" =~ /^$src1$/ AND \"dest\" =~ /^$dest1$/) AND time > now() - 1s ORDER BY time DESC limit 1",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  { "title": "Throughput", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 }, "content": "\n\n\n\n" },
  {
   "title": "Uplink",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"ul\" FROM $database.autogen.network WHERE (\"src\" =~ /^$src1$/ AND \"dest\" =~ /^$dest1$/) AND time > now() - 1s ORDER BY time DESC limit 1",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Downlink",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"dl\" FROM $database.autogen.network WHERE (\"src\" =~ /^$src1$/ AND \"dest\" =~ /^$dest1$/) AND time > now() - 1s ORDER BY time DESC limit 1\n",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Shows latency between source & destination applications",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$scenario$/",
     "query": "SELECT mean(\"lat\") FROM $database.autogen.network WHERE (\"src\" =~ /^$src1$/ AND \"dest\" =~ /^$dest1$/) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Shows Throughput between source & destination applications",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "UL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"ul\") FROM $database.autogen.network WHERE (\"src\" =~ /^$src1$/ AND \"dest\" =~ /^$dest1$/) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "ul" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    },
    {
     "alias": "DL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"dl\") FROM $database.autogen.network WHERE (\"src\" =~ /^$src1$/ AND \"dest\" =~ /^$dest1$/) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "dl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  { "title": "Player 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"lat\" FROM $database.autogen.network WHERE (\"src\" =~ /^$src2$/ AND \"dest\" =~ /^$dest2$/) AND time > now() - 1s ORDER BY time DESC limit 1",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  { "title": "Throughput", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 10 }, "content": "\n\n\n\n" },
  {
   "title": "Uplink",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"ul\" FROM $database.autogen.network WHERE (\"src\" =~ /^$src2$/ AND \"dest\" =~ /^$dest2$/) AND time > now() - 1s ORDER BY time DESC limit 1",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "Downlink",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT \"dl\" FROM $database.autogen.network WHERE (\"src\" =~ /^$src2$/ AND \"dest\" =~ /^$dest2$/) AND time > now() - 1s ORDER BY time DESC limit 1",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Shows latency between source & destination applications",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$scenario$/",
     "query": "SELECT mean(\"lat\") FROM $database.autogen.network WHERE (\"src\" =~ /^$src2$/ AND \"dest\" =~ /^$dest2$/) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Shows Throughput between source & destination applications",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "UL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"ul\") FROM $database.autogen.network WHERE (\"src\" =~ /^$src2$/ AND \"dest\" =~ /^$dest2$/) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "ul" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    },
    {
     "alias": "DL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"dl\") FROM $database.autogen.network WHERE (\"src\" =~ /^$src2$/ AND \"dest\" =~ /^$dest2$/) AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "dl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "events",
     "query": "SELECT type,description FROM $database.autogen.events WHERE $timeFilter ORDER BY time desc LIMIT 100",
     "select": [
      [
       { "params": [ "event" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}