{
 "title": "Wireless Metrics Aggregation",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "database", "query": "show databases" },
   {
    "name": "src",
    "query": "show tag values on $database from gis with key = \"src\""
   }
  ]
 },
 "panels": [
  { "title": "Signals Aggregation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RSRPs",
   "type": "graph",
   "description": "Shows RSRPs between source physical location & destination network locations",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Signal (Mapping)" }
   ],
   "targets": [
    {
     "alias": "[[tag_dest]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$scenario$/",
     "query": "SELECT rsrp FROM $database.autogen.gis WHERE (\"src\" =~ /^$src$/) AND $timeFilter GROUP BY dest",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "RSRQs",
   "type": "graph",
   "description": "Shows RSRQs between source physical location & destination network locations",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Signal (Mapping)" }
   ],
   "targets": [
    {
     "alias": "[[tag_dest]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$scenario$/",
     "query": "SELECT rsrq FROM $database.autogen.gis WHERE (\"src\" =~ /^$src$/) AND $timeFilter GROUP BY dest",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSIs",
   "type": "graph",
   "description": "Shows RSSIs between source physical location & destination network locations",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Signal (Mapping)" }
   ],
   "targets": [
    {
     "alias": "[[tag_dest]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$scenario$/",
     "query": "SELECT rssi FROM $database.autogen.gis WHERE (\"src\" =~ /^$src$/) AND $timeFilter GROUP BY dest",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  { "title": "Distance Aggregation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Distances",
   "type": "graph",
   "description": "Shows distances between source physical location & destination network locations",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Distance (Meters)" }
   ],
   "targets": [
    {
     "alias": "[[tag_dest]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$scenario$/",
     "query": "SELECT dist FROM $database.autogen.gis WHERE (\"src\" =~ /^$src$/) AND $timeFilter GROUP BY dest",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "src", "operator": "=~", "value": "/^$src$/" },
      { "condition": "AND", "key": "dest", "operator": "=~", "value": "/^$dest$/" }
     ]
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Events",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "measurement": "events",
     "query": "SELECT type,description FROM $database.autogen.events WHERE $timeFilter ORDER BY time desc LIMIT 100",
     "select": [
      [
       { "params": [ "event" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}