/*
 * MEEP Virtualization Engine REST API
 *
 * MEEP Virtualization Engine REST API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

import (
	"net/http"
)

func ActivateScenario(w http.ResponseWriter, r *http.Request) {
	veActivateScenario(w, r)
}

func GetActiveScenario(w http.ResponseWriter, r *http.Request) {
	veGetActiveScenario(w, r)
}

func TerminateScenario(w http.ResponseWriter, r *http.Request) {
	veTerminateScenario(w, r)
}
