apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "meep-virt-engine.fullname" . }}
  namespace: {{ .Values.namespace }}
subsets:
- addresses:
    - ip: {{ .Values.service.ip }}
  ports:
    - port: {{ .Values.service.targetPort }}
