---
swagger: "2.0"
info:
  description: "MEEP Mobility Group Manager REST API"
  version: "1.0.0"
  title: "MEEP Mobility Group Manager REST API"
basePath: "/v1"
tags:
- name: "Membership"
- name: "State Transfer"
schemes:
- "http"
paths:
  /mg:
    get:
      tags:
      - "Membership"
      summary: "Retrieve list of Mobility Groups"
      description: ""
      operationId: "getMobilityGroupList"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/MobilityGroup"
        404:
          description: "Not found"
  /mg/{mgName}:
    get:
      tags:
      - "Membership"
      summary: "Retrieve Mobility Groups with provided name"
      description: ""
      operationId: "getMobilityGroup"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/MobilityGroup"
        404:
          description: "Not found"
    post:
      tags:
      - "Membership"
      summary: "Add new Mobility Group"
      description: ""
      operationId: "createMobilityGroup"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      - in: "body"
        name: "mobilityGroup"
        description: "Mobility Group to create/update"
        required: true
        schema:
          $ref: "#/definitions/MobilityGroup"
        x-exportParamName: "MobilityGroup"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        404:
          description: "Not found"
    put:
      tags:
      - "Membership"
      summary: "Update Mobility Group"
      description: ""
      operationId: "setMobilityGroup"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      - in: "body"
        name: "mobilityGroup"
        description: "Mobility Group to create/update"
        required: true
        schema:
          $ref: "#/definitions/MobilityGroup"
        x-exportParamName: "MobilityGroup"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        404:
          description: "Not found"
    delete:
      tags:
      - "Membership"
      summary: "Delete Mobility Group"
      description: ""
      operationId: "deleteMobilityGroup"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      responses:
        200:
          description: "OK"
        404:
          description: "Not found"
  /mg/{mgName}/app:
    get:
      tags:
      - "Membership"
      summary: "Retrieve list of Apps in provided Mobility Group"
      description: ""
      operationId: "getMobilityGroupAppList"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/MobilityGroupApp"
        404:
          description: "Not found"
  /mg/{mgName}/app/{appId}:
    get:
      tags:
      - "Membership"
      summary: "Retrieve App information using provided Mobility Group Name & App\
        \ ID"
      description: ""
      operationId: "getMobilityGroupApp"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      - name: "appId"
        in: "path"
        description: "Mobility Group App Id"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/MobilityGroupApp"
        404:
          description: "Not found"
    post:
      tags:
      - "Membership"
      summary: "Add new Mobility Group App"
      description: ""
      operationId: "createMobilityGroupApp"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      - name: "appId"
        in: "path"
        description: "Mobility Group App Id"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - in: "body"
        name: "mgApp"
        description: "Mobility Group App to create/update"
        required: true
        schema:
          $ref: "#/definitions/MobilityGroupApp"
        x-exportParamName: "MgApp"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        404:
          description: "Not found"
    put:
      tags:
      - "Membership"
      summary: "Update Mobility GroupApp"
      description: ""
      operationId: "setMobilityGroupApp"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      - name: "appId"
        in: "path"
        description: "Mobility Group App Id"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - in: "body"
        name: "mgApp"
        description: "Mobility Group App to create/update"
        required: true
        schema:
          $ref: "#/definitions/MobilityGroupApp"
        x-exportParamName: "MgApp"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        404:
          description: "Not found"
    delete:
      tags:
      - "Membership"
      summary: "Delete Mobility Group App"
      description: ""
      operationId: "deleteMobilityGroupApp"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      - name: "appId"
        in: "path"
        description: "Mobility Group App Id"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      responses:
        200:
          description: "OK"
        404:
          description: "Not found"
  /mg/{mgName}/app/{appId}/ue:
    post:
      tags:
      - "Membership"
      summary: "Add UE to group tracking list"
      description: ""
      operationId: "createMobilityGroupUe"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      - name: "appId"
        in: "path"
        description: "Mobility Group App Id"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - in: "body"
        name: "mgUe"
        description: "Mobility Group UE to create/update"
        required: true
        schema:
          $ref: "#/definitions/MobilityGroupUE"
        x-exportParamName: "MgUe"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        404:
          description: "Not found"
  /mg/{mgName}/app/{appId}/state:
    post:
      tags:
      - "State Transfer"
      summary: "Send state to transfer to peers"
      description: ""
      operationId: "transferAppState"
      produces:
      - "application/json"
      parameters:
      - name: "mgName"
        in: "path"
        description: "Mobility Group name"
        required: true
        type: "string"
        x-exportParamName: "MgName"
      - name: "appId"
        in: "path"
        description: "Mobility Group App Id"
        required: true
        type: "string"
        x-exportParamName: "AppId"
      - in: "body"
        name: "appState"
        description: "Mobility Group App State to transfer"
        required: true
        schema:
          $ref: "#/definitions/MobilityGroupAppState"
        x-exportParamName: "AppState"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        404:
          description: "Not found"
definitions:
  MobilityGroup:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Mobility Group name"
      stateTransferMode:
        type: "string"
        description: "State Transfer mode"
        enum:
        - "STATE-DIRECT"
        - "STATE-MANAGED"
        - "INSTANCE-DIRECT"
        - "INSTANCE-MANAGED"
        - "NONE"
      stateTransferTrigger:
        type: "string"
        description: "State Transfer trigger"
        enum:
        - "NET-LOC-IN-RANGE"
        - "NET-LOC-CHANGE"
        - "GPS-PROXIMITY"
        - "NONE"
      sessionTransferMode:
        type: "string"
        description: "Session Transfer mode"
        enum:
        - "GRACEFUL"
        - "FORCED"
      loadBalancingAlgorithm:
        type: "string"
        description: "Load Balancing Algorithm"
        enum:
        - "HOP-COUNT"
        - "LATENCY"
        - "DISTANCE"
    description: "Mobility Group"
    example:
      loadBalancingAlgorithm: "HOP-COUNT"
      name: "name"
      sessionTransferMode: "GRACEFUL"
      stateTransferTrigger: "NET-LOC-IN-RANGE"
      stateTransferMode: "STATE-DIRECT"
  MobilityGroupApp:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Mobility Group Application Identifier"
      url:
        type: "string"
        description: "Event handler url"
    description: "Mobility Group Application instance"
    example:
      id: "id"
      url: "url"
  MobilityGroupUE:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Mobility Group UE Identifier"
    description: "Mobility Group UE instance"
  MobilityGroupAppState:
    type: "object"
    properties:
      ueId:
        type: "string"
        description: "Mobility Group UE Identifier"
      ueState:
        type: "string"
        description: "Mobility Group Application State for provided UE"
    description: "Mobility Group Application State"
    example:
      ueState: "ueState"
      ueId: "ueId"
parameters:
  appId:
    name: "appId"
    in: "path"
    description: "Mobility Group App Id"
    required: true
    type: "string"
    x-exportParamName: "AppId"
  appState:
    in: "body"
    name: "appState"
    description: "Mobility Group App State to transfer"
    required: true
    schema:
      $ref: "#/definitions/MobilityGroupAppState"
    x-exportParamName: "AppState"
  mgApp:
    in: "body"
    name: "mgApp"
    description: "Mobility Group App to create/update"
    required: true
    schema:
      $ref: "#/definitions/MobilityGroupApp"
    x-exportParamName: "MgApp"
  mgName:
    name: "mgName"
    in: "path"
    description: "Mobility Group name"
    required: true
    type: "string"
    x-exportParamName: "MgName"
  mgUe:
    in: "body"
    name: "mgUe"
    description: "Mobility Group UE to create/update"
    required: true
    schema:
      $ref: "#/definitions/MobilityGroupUE"
    x-exportParamName: "MgUe"
  mobilityGroup:
    in: "body"
    name: "mobilityGroup"
    description: "Mobility Group to create/update"
    required: true
    schema:
      $ref: "#/definitions/MobilityGroup"
    x-exportParamName: "MobilityGroup"
responses:
  Std200:
    description: "OK"
  Std201:
    description: "Created"
  Std202:
    description: "Accepted"
  Std204:
    description: "No content"
  Std304:
    description: "Not modified"
  Std400:
    description: "Bad request"
  Std401:
    description: "Not authorized"
  Std403:
    description: "Forbidden"
  Std404:
    description: "Not found"
  Std409:
    description: "Conflict"
  Std416:
    description: "Requested range not satisfiable"
  Std500:
    description: "Internal server error"
