/**
 * MEEP Demo App API
 * This is the MEEP Demo App API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CallbackData', 'model/Timestamp', 'model/UserEventType', 'model/UserInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CallbackData'), require('./Timestamp'), require('./UserEventType'), require('./UserInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.MeepDemoAppApi) {
      root.MeepDemoAppApi = {};
    }
    root.MeepDemoAppApi.UserTrackingNotification = factory(root.MeepDemoAppApi.ApiClient, root.MeepDemoAppApi.CallbackData, root.MeepDemoAppApi.Timestamp, root.MeepDemoAppApi.UserEventType, root.MeepDemoAppApi.UserInfo);
  }
}(this, function(ApiClient, CallbackData, Timestamp, UserEventType, UserInfo) {
  'use strict';




  /**
   * The UserTrackingNotification model module.
   * @module model/UserTrackingNotification
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>UserTrackingNotification</code>.
   * User tracking notification - callback generated toward an ME app with a user tracking subscription
   * @alias module:model/UserTrackingNotification
   * @class
   * @param callbackData {module:model/CallbackData} 
   * @param userInfo {module:model/UserInfo} 
   * @param timeStamp {module:model/Timestamp} 
   */
  var exports = function(callbackData, userInfo, timeStamp) {
    var _this = this;

    _this['callbackData'] = callbackData;
    _this['userInfo'] = userInfo;
    _this['timeStamp'] = timeStamp;

  };

  /**
   * Constructs a <code>UserTrackingNotification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserTrackingNotification} obj Optional instance to populate.
   * @return {module:model/UserTrackingNotification} The populated <code>UserTrackingNotification</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('callbackData')) {
        obj['callbackData'] = CallbackData.constructFromObject(data['callbackData']);
      }
      if (data.hasOwnProperty('userInfo')) {
        obj['userInfo'] = UserInfo.constructFromObject(data['userInfo']);
      }
      if (data.hasOwnProperty('timeStamp')) {
        obj['timeStamp'] = Timestamp.constructFromObject(data['timeStamp']);
      }
      if (data.hasOwnProperty('userEventType')) {
        obj['userEventType'] = UserEventType.constructFromObject(data['userEventType']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CallbackData} callbackData
   */
  exports.prototype['callbackData'] = undefined;
  /**
   * @member {module:model/UserInfo} userInfo
   */
  exports.prototype['userInfo'] = undefined;
  /**
   * @member {module:model/Timestamp} timeStamp
   */
  exports.prototype['timeStamp'] = undefined;
  /**
   * @member {module:model/UserEventType} userEventType
   */
  exports.prototype['userEventType'] = undefined;



  return exports;
}));


