# Default values for meep-vis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  dependencies:
    system:
      {{- if not .IsMepService }}
      - kube-dns
      {{- end }}
    namespace:

image:
  repository: meep-docker-registry:30001/meep-vis
  tag: latest
  pullPolicy: Always
  env:
    MEEP_INSTANCE_ID: {{.InstanceId}}
    MEEP_SANDBOX_NAME: {{.SandboxName}}
    MEEP_SVC_PATH: /vis/v2
    MEEP_HOST_URL: {{.HostUrl}}
    MEEP_BROKER: mqtt://test.mosquito.org:1338
    MEEP_POA_LIST: poa-5g1
    {{- if .IsMepService }}
    MEEP_MEP_NAME: {{.MepName}}
    {{- end }}
    {{- if eq .AppEnablement "local" }}
    MEEP_APP_ENABLEMENT: {{.MepName}}-meep-app-enablement
    {{- else if eq .AppEnablement "global" }}
    MEEP_APP_ENABLEMENT: meep-app-enablement
    {{- end }}
    MEEP_PREDICT_MODEL_SUPPORTED: ""
    {{- range .Env}}
    {{.}}
    {{- end}}

service:
  {{- if .IsMepService }}
  name: {{.MepName}}-meep-vis
  {{- else }}
  name: meep-vis
  {{- end }}
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        {{- if .IsMepService }}
        - /{{.SandboxName}}/{{.MepName}}/vis
        {{- else }}
        - /{{.SandboxName}}/vis
        {{- end }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .HttpsOnly }}
    {{- if .IsMepService }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{.SandboxName}}/{{.MepName}}/vis(/|$)(.*)$ /vis/$2 break;
    {{- else }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{.SandboxName}}/vis(/|$)(.*)$ /vis/$2 break;
    {{- end }}
    {{- if .AuthEnabled }}
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-vis&sbox={{.SandboxName}}&mep={{.MepName}}
    {{- end }}
  labels: {}
  tls:

prometheus:
  monitor:
    enabled: true
    port: 9000
    interval: 10s
    additionalLabels: {}
    relabelings: []
    scrapeTimeout: 5s

codecov:
  enabled: false
  location: "<WORKDIR>/codecov/meep-vis"

meepOrigin: core
