image:
  registry: docker.io
  repository: redislabs/rejson
  tag: latest
  pullPolicy: IfNotPresent

usePassword: false

## Persist data to a persistent volume
persistence: {}
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

master:
  disableCommands: ""
  persistence:
    enabled: false

meepOrigin: core

