/*
 * MEEP Mobility Group Application REST API
 *
 * MEEP Mobility Group Application REST API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Mobility Group Application State
type MobilityGroupAppState struct {

	// Mobility Group UE Identifier
	UeId string `json:"ueId,omitempty"`

	// Mobility Group Application State for provided UE
	UeState string `json:"ueState,omitempty"`
}
