/*
 * Copyright (c) 2022  The AdvantEDGE Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * AdvantEDGE Sandbox Controller REST API
 * This API is the main Sandbox Controller API for scenario deployment & event injection <p>**Micro-service**<br>[meep-sandbox-ctrl](https://github.com/InterDigitalInc/AdvantEDGE/tree/master/go-apps/meep-sandbox-ctrl) <p>**Type & Usage**<br>Platform runtime interface to manage active scenarios and inject events in AdvantEDGE platform <p>**Details**<br>API details available at _your-AdvantEDGE-ip-address/api_
 *
 * OpenAPI spec version: 1.0.0
 * Contact: AdvantEDGE@InterDigital.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdvantEdgeSandboxControllerRestApi);
  }
}(this, function(expect, AdvantEdgeSandboxControllerRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AdvantEdgeSandboxControllerRestApi.ConnectivityApi();
  });

  describe('(package)', function() {
    describe('ConnectivityApi', function() {
      describe('createPduSession', function() {
        it('should call createPduSession successfully', function(done) {
          // TODO: uncomment, update parameter values for createPduSession call
          /*
          var ueName = "ueName_example";
          var pduSessionId = "pduSessionId_example";
          var pduSessionInfo = new AdvantEdgeSandboxControllerRestApi.PDUSessionInfo();
          pduSessionInfo.dnn = "";

          instance.createPduSession(ueName, pduSessionId, pduSessionInfo, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPduSessionList', function() {
        it('should call getPduSessionList successfully', function(done) {
          // TODO: uncomment, update parameter values for getPduSessionList call and complete the assertions
          /*
          var opts = {};
          opts.ue = "ue_example";
          opts.id = "id_example";

          instance.getPduSessionList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AdvantEdgeSandboxControllerRestApi.PDUSessionList);
            {
              let dataCtr = data.sessions;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(AdvantEdgeSandboxControllerRestApi.PDUSession);
                expect(data.ue).to.be.a('string');
                expect(data.ue).to.be("");
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("");
                expect(data.info).to.be.a(AdvantEdgeSandboxControllerRestApi.PDUSessionInfo);
                      expect(data.info.dnn).to.be.a('string');
                  expect(data.info.dnn).to.be("");
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('terminatePduSession', function() {
        it('should call terminatePduSession successfully', function(done) {
          // TODO: uncomment, update parameter values for terminatePduSession call
          /*
          var ueName = "ueName_example";
          var pduSessionId = "pduSessionId_example";

          instance.terminatePduSession(ueName, pduSessionId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
